### ISSUE TITLE
Reading Fifo continuosly

### ISSUE THREAD

**Issue by cool112624** [danjperron/mpu6050TestInC#3]
Hi, first of all thank you for your code 
What I was trying is to read continuosly from fifo and write to file, but I am confused on the convert data
this is the error that I face, Can you help me? 
Thank you in advance

![Screenshot_2023_03_01_15_59_26](https://user-images.githubusercontent.com/51593747/222078911-9f9dd9b5-8b64-4e91-8436-e3fdb20e0970.png)

<details>
<summary>Code</summary>

```
# Import Library
import MPU6050_lib_3 as MPU6050
import RPi.GPIO as GPIO
import time

pin = 21
GPIO.setmode(GPIO.BCM)
GPIO.setup(pin, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)

# TargetSampleNumber= 1024
# TargetRate =  33    # frequency =  8000 / ( integr value + 1)  minimum frequency=32,25

# Adjust read rate
TargetRate = 1000 # max = 2000Hz 

# Setting Sensor
mpu6050 = MPU6050.MPU6050()
mpu6050.setup()
mpu6050.setGResolution(2)
mpu6050.setSampleRate(TargetRate)
mpu6050.resetFifo()
mpu6050.enableFifo(True)
time.sleep(0.01)

print ("Capturing {0} samples/sec".format(mpu6050.SampleRate))
value=[]
#FO = open("RawData.txt","a")


for i in range(10000):
    f = open("data.txt", 'a')
    t1 = time.time()
    trigger = GPIO.input(pin)
    value = mpu6050.readDataFromFifo()
    I = mpu6050.convertData(value)
    print(I.Gyrox)
    f.write("{0:1.1f}\t{1:1.1f}\t".format(t1,trigger))
    f.write("{0:0.3f}\t{1:2.3f}\t{2:2.3f}\t".format(I.Gx,I.Gy,I.Gz))
    f.write("{0:3.3f}\t{1:3.3f}\t{2:3.3f}\t{3:3.2f}\n".format(I.Gyrox,I.Gyroy,I.Gyroz,I.Temperature))
    value.clear()
    t2 = time.time()
    print((t2-t1)*1000)

```

**Comment by danjperron** [comment]
Hi,
 
 the code was made for python2.

 on python3 you just need to get rid of buffer






> 
>  def convertData(self,ListData):
> 
>  ShortData = struct.unpack(">hhhhhhh", bytearray(ListData))
> 
>  .....etc...
> 



Explanation of the code

***@***.***:~/mpu6050TestInC $ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.

# I will load the library with buffer removed from convertData
# and manually read the sensor

#first import the needed library
>>> import MPU6050
>>> import struct

# initialize the mpu6050
>>> mpu6050 = MPU6050.MPU6050()
>>> mpu6050.setup()

#ok we need to create an smbus object since I will execute fonction outside the library
>>> import smbus
>>> bus = smbus.SMBus(1)

#here I'm reading 14 bytes! This is the three accelarations, three gyros and the last one is the temperature
>>> Gdata = bus.read_i2c_block_data(mpu6050.MPU6050_ADDRESS, mpu6050.MPU6050_RA_ACCEL_XOUT_H,14)
>>> Gdata
[243, 128, 16, 128, 195, 72, 238, 240, 246, 70, 250, 183, 252, 97]

#ok I want to extract the 7 values which are 16bits unsigned
# best way is use struct unpack but it needs to be a stream of bytes so in python3 bytearray directly
# no need to convert to buffer
>>> struct.unpack(">hhhhhhh",bytearray(Gdata))
(-3200, 4224, -15544, -4368, -2490, -1353, -927)
>>>


Best regards,

Daniel

**Comment by cool112624** [comment]
Thank you for your detail explaination

I use MPU6050 library before and sucess, but I want to read sensor value every 1ms, but using this library I can only read sensor value fatest at 1.8ms

so I want to read from sensor Fifo

**Comment by danjperron** [comment]
`I use MPU6050 library before and sucess, but I want to read sensor value every 1ms, but using this library I can only read sensor value fatest at 1.8ms`

I'm confuse is it about my library or another one?

If it is mine you should use the C version.

**Comment by cool112624** [comment]
I am sorry,  I ask in wrong place
but thank you for your kind explaination
appreciated
